### ISSUE TITLE
Need to clarify how "movement phases" and associated numbers work

### ISSUE THREAD

**Issue by agaos1** [agaos1/R_for_sea_turtle_spatial_analysis#1]
I am in the process of eliminating irrelevant locations and/or reassigning to different movement stages in "Step 2 - Detect dispersal". However, I am not clear on how the phases 1, 2, etc. actually work (see code from step 2 below). I initially thought it was always  case that 1=pre-migration, 2=migration, and 3=post-migration? However, as I'm playing with things, it appears this is not the case. 

Does the number depend on what the turtle/track did? Examples to clarify:
Example 1: A turtle was released and immediately starting migrating, then arrived at a foraging ground a few days later. So, 1=migration and 2=foraging ground locations.
Example 2: A turtle was released and remained in a single foraging location. So, 1=foraging ground location.
Example 3: a turtle was released, hung out in a foraging ground location for a few weeks, then migrated. So, 1=foraging, 2=migraton.
Example 3: a turtle was released, hung out in a foraging ground location for a few weeks, then migrated for a week, then arrived at a foraging ground. So, 1=foraging location one, 2=migration, 3=foraging location two.

Is this correct?

locs$migr_tbl[[37]][1,]$end <- mdy("8/23/2022")
locs$migr_tbl[[37]][2,]$start <- mdy("8/23/2022")

**Comment by dsjohnson** [comment]
Yes you're correct. There is also a column in the table labeled 'migr_event' or something like that where a 1 indicates a migration phase and a 0 is a stationary phase.
