### ISSUE TITLE
Just a reminder if you have time!

### ISSUE THREAD

**Issue by agaos1** [agaos1/R_for_sea_turtle_spatial_analysis#2]
Hope the conference is going well! I just wanted to send a reminder that _if you have time_, I would greatly appreciate it if you can work on updating/creating the code for the other three pending steps in the turtle spatial ecology "package":

A_Visualizing tracks.qmd |
C_Group UDs.qmd 
D_Land Maps.qmd

Not trying to pester, just want to keep this at the top of your list so I can advance the manuscript I'm working on as possible. Even if you can't work on this until you get back from the conference, I would really appreciate it if it could a priority for you upon your time. 

Many Mahalos in advance.
Gaos

**Comment by dsjohnson** [comment]
I didn't have time at the conference, but I'll be back at first thing Monday.
